repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: poetry run ruff check --force-exclude --fix
        language: system
        types_or: [python, pyi]
        require_serial: true
        minimum_pre_commit_version: 2.9.0
      - id: ruff-format
        name: ruff-format
        entry: poetry run ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true
        minimum_pre_commit_version: 2.9.0
      - id: prettier
        name: prettier
        entry: npx prettier --write --list-different --ignore-unknown
        language: system
        types: [text]
        require_serial: false
      - id: eslint
        name: eslint
        entry: npx eslint
        language: system
        types: [javascript]
        require_serial: false
      - id: stylelint
        name: stylelint
        entry: npx stylelint
        language: system
        types: [css, sass, scss]
